export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const CAROUSEL_LIST_REQUEST = 'CAROUSEL_LIST_REQUEST';
export const CAROUSEL_LIST_SUCCESS = 'CAROUSEL_LIST_SUCCESS';
export const CAROUSEL_LIST_FAIL = ' CAROUSEL_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'CAROUSEL_LIST_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

